07-19 09:59:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07-19 09:59:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07-19 10:00:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "RECIPE" not found; SQL statement:
CREATE TABLE IF NOT EXISTS  RECIPE_INGREDIENT(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	RECIPE_ID INT NOT NULL,
	QUANTITY VARCHAR(250) NOT NULL,
	MEASUREMENT VARCHAR(250) NOT NULL,
	INGREDIENT_NAME VARCHAR(250) NOT NULL,
	
	CONSTRAINT FK_RECIPE_ID FOREIGN KEY(RECIPE_ID) REFERENCES RECIPE(ID)
) [42102-172]
07-19 10:00:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "RECIPE_INGREDIENT" not found; SQL statement:
INSERT INTO RECIPE_INGREDIENT(ID, RECIPE_ID, QUANTITY, MEASUREMENT, INGREDIENT_NAME) VALUES (1, 1, '3 1/2', 'cups', 'whole milk') [42102-172]
07-19 10:00:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "RECIPE_INGREDIENT" not found; SQL statement:
INSERT INTO RECIPE_INGREDIENT(ID, RECIPE_ID, QUANTITY, MEASUREMENT, INGREDIENT_NAME) VALUES (2, 1, '2', 'ounces', 'cocoa') [42102-172]
07-20 09:15:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07-20 09:15:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07-20 09:15:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07-20 09:15:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:428)
	at com.onseven.dbvis.g.B.C.ā(Z:344)
	at com.onseven.dbvis.g.B.F$A.call(Z:1474)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
